Solved export error in index.d.ts
Solution for error "error TS2694: Namespace 'angular' has no exported member 'gettext'.".
Module "angular" is now imported. The "angular.gettext" namespace declaration has been changed to instead extend the angular module.